name: Dungeon
main: com.bukkit.toasterktn.Dungeon.Dungeon
version: 0.5
commands: 
   regeneratechunk:
      description: Regen a Chunk
      usage: /<command> [x] [z]
      aliases: 
         - regc
         - cr
   dungeon:
      description: Ports you in the Dungeon world.
      usage: /<command>
      aliases:
         - dp
   initdungeonarea:
      description: create the Start Area for the Dungeons.
      usage: /<command>
      aliases:
         - initdun